package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClientUninstallPasswd generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "ClientUninstallPasswd", catalog = "dcms_db")
public class ClientUninstallPasswd implements java.io.Serializable {

    private Integer id;
    private String passwd;
    private Long createTime;
    private String description;
    private Integer syncNum;
    private Integer unsyncNum;

    public ClientUninstallPasswd() {
    }

    public ClientUninstallPasswd(String passwd, Long createTime, String description, Integer syncNum,
            Integer unsyncNum) {
        this.passwd = passwd;
        this.createTime = createTime;
        this.description = description;
        this.syncNum = syncNum;
        this.unsyncNum = unsyncNum;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "passwd", length = 256, columnDefinition = "")
    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    @Column(name = "createTime")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "description", length = 256, columnDefinition = "")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "syncNum")
    public Integer getSyncNum() {
        return this.syncNum;
    }

    public void setSyncNum(Integer syncNum) {
        this.syncNum = syncNum;
    }

    @Column(name = "unsyncNum")
    public Integer getUnsyncNum() {
        return this.unsyncNum;
    }

    public void setUnsyncNum(Integer unsyncNum) {
        this.unsyncNum = unsyncNum;
    }

}
