package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClientPatch generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "ClientPatch", catalog = "dcms_db")
public class ClientPatch implements java.io.Serializable {

    private Integer id;
    private StorageLocation storageLocation;
    private Long createTime;
    private String description;
    private String name;
    private Long fileSize;
    private String fileMd5;
    private Integer versionCode;
    private String versionName;
    private String osType;
    private Integer versionType;

    public ClientPatch() {
    }

    public ClientPatch(StorageLocation storageLocation, Long createTime, String description, String name, Long fileSize,
            String fileMd5, Integer versionCode, String versionName, String osType, Integer versionType) {
        this.storageLocation = storageLocation;
        this.createTime = createTime;
        this.description = description;
        this.name = name;
        this.fileSize = fileSize;
        this.fileMd5 = fileMd5;
        this.versionCode = versionCode;
        this.versionName = versionName;
        this.osType = osType;
        this.versionType = versionType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkLocationId")
    public StorageLocation getStorageLocation() {
        return this.storageLocation;
    }

    public void setStorageLocation(StorageLocation storageLocation) {
        this.storageLocation = storageLocation;
    }

    @Column(name = "createTime")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "description", length = 256, columnDefinition = "")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "name", length = 256, columnDefinition = "")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "fileSize")
    public Long getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Column(name = "fileMd5", length = 256, columnDefinition = "")
    public String getFileMd5() {
        return this.fileMd5;
    }

    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    @Column(name = "versionCode")
    public Integer getVersionCode() {
        return this.versionCode;
    }

    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    @Column(name = "versionName", length = 256, columnDefinition = "")
    public String getVersionName() {
        return this.versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    @Column(name = "osType", length = 256, columnDefinition = "")
    public String getOsType() {
        return this.osType;
    }

    public void setOsType(String osType) {
        this.osType = osType;
    }

    @Column(name = "versionType")
    public Integer getVersionType() {
        return this.versionType;
    }

    public void setVersionType(Integer versionType) {
        this.versionType = versionType;
    }

}
