package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "Department", catalog = "dcms_db")
public class Department implements java.io.Serializable {

    private String pkDid;
    private String fkParentId;
    private String name;
    private String description;
    private Integer departmentState;
    private Integer root;
    private List<Group> groups = new ArrayList<Group>(0);
    private List<UserToDepartment> userToDepartments = new ArrayList<UserToDepartment>(0);

    public Department() {
    }

    public Department(String pkDid) {
        this.pkDid = pkDid;
    }

    public Department(String pkDid, String fkParentId, String name, String description, Integer departmentState,
            Integer root, List<Group> groups, List<UserToDepartment> userToDepartments) {
        this.pkDid = pkDid;
        this.fkParentId = fkParentId;
        this.name = name;
        this.description = description;
        this.departmentState = departmentState;
        this.root = root;
        this.groups = groups;
        this.userToDepartments = userToDepartments;
    }

    @Id

    @Column(name = "pkDid", unique = true, nullable = false, length = 256)
    public String getPkDid() {
        return this.pkDid;
    }

    public void setPkDid(String pkDid) {
        this.pkDid = pkDid;
    }

    @Column(name = "fkParentId", length = 256, columnDefinition = "")
    public String getFkParentId() {
        return this.fkParentId;
    }

    public void setFkParentId(String fkParentId) {
        this.fkParentId = fkParentId;
    }

    @Column(name = "name", length = 256, columnDefinition = "")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 256, columnDefinition = "")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "departmentState")
    public Integer getDepartmentState() {
        return this.departmentState;
    }

    public void setDepartmentState(Integer departmentState) {
        this.departmentState = departmentState;
    }

    @Column(name = "root")
    public Integer getRoot() {
        return this.root;
    }

    public void setRoot(Integer root) {
        this.root = root;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
    public List<Group> getGroups() {
        return this.groups;
    }

    public void setGroups(List<Group> groups) {
        this.groups = groups;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
    public List<UserToDepartment> getUserToDepartments() {
        return this.userToDepartments;
    }

    public void setUserToDepartments(List<UserToDepartment> userToDepartments) {
        this.userToDepartments = userToDepartments;
    }

}
