package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FileAccessScope generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Table(name = "FileAnalysis", catalog = "dcms_db")
public class FileAnalysis implements java.io.Serializable {

    private String analysisId;
    private String fkFid;
    private String md5;
    private String fileName;
    private String filePath;
    private String keywordResult;
    private String description;
    private Integer execState;

    public FileAnalysis() {
    }

    public FileAnalysis(String analysisId) {
        this.analysisId = analysisId;
    }

    public FileAnalysis(String analysisId, String fkFid, String md5, String fileName, String filePath, String keywordResult,
            String description, Integer execState) {
        this.analysisId = analysisId;
        this.fkFid = fkFid;
        this.md5 = md5;
        this.fileName = fileName;
        this.filePath = filePath;
        this.keywordResult = keywordResult;
        this.description = description;
        this.execState = execState;
    }

    @Id

    @Column(name = "analysisId", unique = true, nullable = false, length = 40)
    public String getAnalysisId() {
        return this.analysisId;
    }

    public void setAnalysisId(String analysisId) {
        this.analysisId = analysisId;
    }

    @Column(name = "fkFid", length = 40)
    public String getFkFid() {
        return fkFid;
    }

    public void setFkFid(String fkFid) {
        this.fkFid = fkFid;
    }

    @Column(name = "md5", length = 40, columnDefinition = "")
    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    @Column(name = "fileName", length = 256, columnDefinition = "")
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "filePath", length = 1024, columnDefinition = "")
    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(name = "keywordResult", columnDefinition = "text")
    public String getKeywordResult() {
        return keywordResult;
    }

    public void setKeywordResult(String keywordResult) {
        this.keywordResult = keywordResult;
    }

    @Column(name = "description", length = 256, columnDefinition = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "execState")
    public Integer getExecState() {
        return execState;
    }

    public void setExecState(Integer execState) {
        this.execState = execState;
    }

}
