package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FileLevelDecideBasis generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Table(name = "FileLevelDecideBasis", catalog = "dcms_db")
public class FileLevelDecideBasis implements java.io.Serializable {

    private Integer id;
    private Integer basisType;
    private Integer basisLevel;
    private String basisItem;
    private String basisClass;
    private String basisName;

    public FileLevelDecideBasis() {
    }

    public FileLevelDecideBasis(Integer basisType, Integer basisLevel, String basisItem, String basisClass,
            String basisName) {
        this.basisType = basisType;
        this.basisLevel = basisLevel;
        this.basisItem = basisItem;
        this.basisClass = basisClass;
        this.basisName = basisName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "basisType")
    public Integer getBasisType() {
        return this.basisType;
    }

    public void setBasisType(Integer basisType) {
        this.basisType = basisType;
    }

    @Column(name = "basisLevel")
    public Integer getBasisLevel() {
        return this.basisLevel;
    }

    public void setBasisLevel(Integer basisLevel) {
        this.basisLevel = basisLevel;
    }

    @Column(name = "basisItem", length = 1024, columnDefinition = "")
    public String getBasisItem() {
        return basisItem;
    }

    public void setBasisItem(String basisItem) {
        this.basisItem = basisItem;
    }

    @Column(name = "basisClass", length = 256, columnDefinition = "")
    public String getBasisClass() {
        return basisClass;
    }

    public void setBasisClass(String basisClass) {
        this.basisClass = basisClass;
    }

    @Column(name = "basisName", length = 256, columnDefinition = "")
    public String getBasisName() {
        return basisName;
    }

    public void setBasisName(String basisName) {
        this.basisName = basisName;
    }

}
