package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FileAccessScope generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "FileAccessScope", catalog = "dcms_db")
public class FileAccessScope implements java.io.Serializable {

    private Integer id;
    private String fkFid;
    private String unitNo;
    private String fkUid;

    public FileAccessScope() {
    }

    public FileAccessScope(String unitNo) {
        this.unitNo = unitNo;
    }

    public FileAccessScope(String fkFid, String unitNo, String fkUid) {
        this.fkFid = fkFid;
        this.unitNo = unitNo;
        this.fkUid = fkUid;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "fkFid", length = 256, columnDefinition = "")
    public String getFkFid() {
        return this.fkFid;
    }

    public void setFkFid(String fkFid) {
        this.fkFid = fkFid;
    }

    @Column(name = "unitNo", nullable = false, length = 256)
    public String getUnitNo() {
        return this.unitNo;
    }

    public void setUnitNo(String unitNo) {
        this.unitNo = unitNo;
    }

    @Column(name = "fkUid", length = 256, columnDefinition = "")
    public String getFkUid() {
        return this.fkUid;
    }

    public void setFkUid(String fkUid) {
        this.fkUid = fkUid;
    }

}
