package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Table(name = "File", catalog = "dcms_db")
public class File implements java.io.Serializable {

    private String pkFid;
    private String fkParentFid;
    private String fkOrigFid;
    private StorageLocation storageLocation;
    private User userByFkFileDispatchUid;
    private User userByFkFileLevelDecideUid;
    private User userByFkFileCreateUid;
    private Integer fileState;
    private String name;
    private String suffix;
    private Integer markVersion;
    private Integer urgency;
    private Integer fileLevel;
    private String validPeriod;
    private Integer durationType;
    private String durationDescription;
    private Long fileCreateTime;
    private Long fileLevelDecideTime;
    private Long fileDispatchTime;
    private Long fileLevelChangeTime;
    private Long fileDecryptTime;
    private String description;
    private String majorUnit;
    private String minorUnit;
    private String basis;
    private Integer basisType;
    private String basisDesc;
    private Long fileSize;
    private String fileMd5;
    private String fileDispatchExpect;
    private String issueNumber;
    private Integer docNumber;
    private Integer duplicationAmount;
    private String fileExtension;
    private Integer contentRead;
    private Integer contentPrint;
    private Integer contentPrintHideWater;
    private Integer contentModify;
    private Integer contentScreenShot;
    private Integer contentCopy;
    private Integer fileCopy;
    private Integer fileSaveCopy;
    private String history;
    private String business;
    private Integer outOfDate;
    private List<ClientLog> clientLogsForFkSrcFid = new ArrayList<ClientLog>(0);
    private List<FileLevelChangeHistory> fileLevelChangeHistories = new ArrayList<FileLevelChangeHistory>(0);

    public File() {
    }

    public File(String pkFid) {
        this.pkFid = pkFid;
    }

    public File(String pkFid, String fkParentFid, String fkOrigFid, StorageLocation storageLocation,
            User userByFkFileDispatchUid, User userByFkFileLevelDecideUid, User userByFkFileCreateUid,
            Integer fileState, String name, String suffix, Integer markVersion, Integer urgency, Integer fileLevel,
            String validPeriod, Integer durationType, String durationDescription, Long fileCreateTime,
            Long fileLevelDecideTime, Long fileDispatchTime, Long fileLevelChangeTime, Long fileDecryptTime,
            String description, String majorUnit, String minorUnit, String basis, Integer basisType, String basisDesc,
            Long fileSize, String fileMd5, String fileDispatchExpect, String issueNumber, Integer docNumber,
            Integer duplicationAmount, String fileExtension, Integer contentRead, Integer contentPrint,
            Integer contentPrintHideWater, Integer contentModify, Integer contentScreenShot, Integer contentCopy,
            Integer fileCopy, Integer fileSaveCopy, String history, String business, Integer outOfDate,
            List<ClientLog> clientLogsForFkSrcFid, List<FileLevelChangeHistory> fileLevelChangeHistories) {
        this.pkFid = pkFid;
        this.fkParentFid = fkParentFid;
        this.fkOrigFid = fkOrigFid;
        this.storageLocation = storageLocation;
        this.userByFkFileDispatchUid = userByFkFileDispatchUid;
        this.userByFkFileLevelDecideUid = userByFkFileLevelDecideUid;
        this.userByFkFileCreateUid = userByFkFileCreateUid;
        this.fileState = fileState;
        this.name = name;
        this.suffix = suffix;
        this.markVersion = markVersion;
        this.urgency = urgency;
        this.fileLevel = fileLevel;
        this.validPeriod = validPeriod;
        this.durationType = durationType;
        this.durationDescription = durationDescription;
        this.fileCreateTime = fileCreateTime;
        this.fileLevelDecideTime = fileLevelDecideTime;
        this.fileDispatchTime = fileDispatchTime;
        this.fileLevelChangeTime = fileLevelChangeTime;
        this.fileDecryptTime = fileDecryptTime;
        this.description = description;
        this.majorUnit = majorUnit;
        this.minorUnit = minorUnit;
        this.basis = basis;
        this.basisType = basisType;
        this.basisDesc = basisDesc;
        this.fileSize = fileSize;
        this.fileMd5 = fileMd5;
        this.fileDispatchExpect = fileDispatchExpect;
        this.issueNumber = issueNumber;
        this.docNumber = docNumber;
        this.duplicationAmount = duplicationAmount;
        this.fileExtension = fileExtension;
        this.contentRead = contentRead;
        this.contentPrint = contentPrint;
        this.contentPrintHideWater = contentPrintHideWater;
        this.contentModify = contentModify;
        this.contentScreenShot = contentScreenShot;
        this.contentCopy = contentCopy;
        this.fileCopy = fileCopy;
        this.fileSaveCopy = fileSaveCopy;
        this.history = history;
        this.business = business;
        this.outOfDate = outOfDate;
        this.clientLogsForFkSrcFid = clientLogsForFkSrcFid;
        this.fileLevelChangeHistories = fileLevelChangeHistories;
    }

    @Id

    @Column(name = "pkFid", unique = true, nullable = false, length = 256)
    public String getPkFid() {
        return this.pkFid;
    }

    public void setPkFid(String pkFid) {
        this.pkFid = pkFid;
    }

    @Column(name = "fkParentFid")
    public String getFkParentFid() {
        return fkParentFid;
    }

    public void setFkParentFid(String fkParentFid) {
        this.fkParentFid = fkParentFid;
    }

    @Column(name = "fkOrigFid")
    public String getFkOrigFid() {
        return fkOrigFid;
    }

    public void setFkOrigFid(String fkOrigFid) {
        this.fkOrigFid = fkOrigFid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkLocationId")
    public StorageLocation getStorageLocation() {
        return this.storageLocation;
    }

    public void setStorageLocation(StorageLocation storageLocation) {
        this.storageLocation = storageLocation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileDispatchUid")
    public User getUserByFkFileDispatchUid() {
        return this.userByFkFileDispatchUid;
    }

    public void setUserByFkFileDispatchUid(User userByFkFileDispatchUid) {
        this.userByFkFileDispatchUid = userByFkFileDispatchUid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileLevelDecideUid")
    public User getUserByFkFileLevelDecideUid() {
        return this.userByFkFileLevelDecideUid;
    }

    public void setUserByFkFileLevelDecideUid(User userByFkFileLevelDecideUid) {
        this.userByFkFileLevelDecideUid = userByFkFileLevelDecideUid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileCreateUid")
    public User getUserByFkFileCreateUid() {
        return this.userByFkFileCreateUid;
    }

    public void setUserByFkFileCreateUid(User userByFkFileCreateUid) {
        this.userByFkFileCreateUid = userByFkFileCreateUid;
    }

    @Column(name = "fileState")
    public Integer getFileState() {
        return this.fileState;
    }

    public void setFileState(Integer fileState) {
        this.fileState = fileState;
    }

    @Column(name = "name", length = 256, columnDefinition = "")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "suffix", length = 256, columnDefinition = "")
    public String getSuffix() {
        return this.suffix;
    }

    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    @Column(name = "markVersion")
    public Integer getMarkVersion() {
        return this.markVersion;
    }

    public void setMarkVersion(Integer markVersion) {
        this.markVersion = markVersion;
    }

    @Column(name = "urgency")
    public Integer getUrgency() {
        return this.urgency;
    }

    public void setUrgency(Integer urgency) {
        this.urgency = urgency;
    }

    @Column(name = "fileLevel")
    public Integer getFileLevel() {
        return this.fileLevel;
    }

    public void setFileLevel(Integer fileLevel) {
        this.fileLevel = fileLevel;
    }

    @Column(name = "validPeriod", columnDefinition = "")
    public String getValidPeriod() {
        return this.validPeriod;
    }

    public void setValidPeriod(String validPeriod) {
        this.validPeriod = validPeriod;
    }

    @Column(name = "durationType")
    public Integer getDurationType() {
        return this.durationType;
    }

    public void setDurationType(Integer durationType) {
        this.durationType = durationType;
    }

    @Column(name = "durationDescription", length = 1024, columnDefinition = "")
    public String getDurationDescription() {
        return this.durationDescription;
    }

    public void setDurationDescription(String durationDescription) {
        this.durationDescription = durationDescription;
    }

    @Column(name = "fileCreateTime")
    public Long getFileCreateTime() {
        return this.fileCreateTime;
    }

    public void setFileCreateTime(Long fileCreateTime) {
        this.fileCreateTime = fileCreateTime;
    }

    @Column(name = "fileLevelDecideTime")
    public Long getFileLevelDecideTime() {
        return this.fileLevelDecideTime;
    }

    public void setFileLevelDecideTime(Long fileLevelDecideTime) {
        this.fileLevelDecideTime = fileLevelDecideTime;
    }

    @Column(name = "fileDispatchTime")
    public Long getFileDispatchTime() {
        return this.fileDispatchTime;
    }

    public void setFileDispatchTime(Long fileDispatchTime) {
        this.fileDispatchTime = fileDispatchTime;
    }

    @Column(name = "fileLevelChangeTime")
    public Long getFileLevelChangeTime() {
        return this.fileLevelChangeTime;
    }

    public void setFileLevelChangeTime(Long fileLevelChangeTime) {
        this.fileLevelChangeTime = fileLevelChangeTime;
    }

    @Column(name = "fileDecryptTime")
    public Long getFileDecryptTime() {
        return this.fileDecryptTime;
    }

    public void setFileDecryptTime(Long fileDecryptTime) {
        this.fileDecryptTime = fileDecryptTime;
    }

    @Column(name = "description", length = 256, columnDefinition = "")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "majorUnit", length = 256, columnDefinition = "")
    public String getMajorUnit() {
        return this.majorUnit;
    }

    public void setMajorUnit(String majorUnit) {
        this.majorUnit = majorUnit;
    }

    @Column(name = "minorUnit", length = 2048, columnDefinition = "")
    public String getMinorUnit() {
        return this.minorUnit;
    }

    public void setMinorUnit(String minorUnit) {
        this.minorUnit = minorUnit;
    }

    @Column(name = "basis", columnDefinition = "text")
    public String getBasis() {
        return this.basis;
    }

    public void setBasis(String basis) {
        this.basis = basis;
    }

    @Column(name = "basisType")
    public Integer getBasisType() {
        return this.basisType;
    }

    public void setBasisType(Integer basisType) {
        this.basisType = basisType;
    }

    @Column(name = "basisDesc", length = 1024, columnDefinition = "")
    public String getBasisDesc() {
        return this.basisDesc;
    }

    public void setBasisDesc(String basisDesc) {
        this.basisDesc = basisDesc;
    }

    @Column(name = "fileSize")
    public Long getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Column(name = "fileMd5", length = 256, columnDefinition = "")
    public String getFileMd5() {
        return this.fileMd5;
    }

    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    @Column(name = "fileDispatchExpect", length = 1024, columnDefinition = "")
    public String getFileDispatchExpect() {
        return this.fileDispatchExpect;
    }

    public void setFileDispatchExpect(String fileDispatchExpect) {
        this.fileDispatchExpect = fileDispatchExpect;
    }

    @Column(name = "issueNumber", length = 50, columnDefinition = "")
    public String getIssueNumber() {
        return this.issueNumber;
    }

    public void setIssueNumber(String issueNumber) {
        this.issueNumber = issueNumber;
    }

    @Column(name = "docNumber")
    public Integer getDocNumber() {
        return this.docNumber;
    }

    public void setDocNumber(Integer docNumber) {
        this.docNumber = docNumber;
    }

    @Column(name = "duplicationAmount")
    public Integer getDuplicationAmount() {
        return this.duplicationAmount;
    }

    public void setDuplicationAmount(Integer duplicationAmount) {
        this.duplicationAmount = duplicationAmount;
    }

    @Column(name = "fileExtension", length = 1024, columnDefinition = "")
    public String getFileExtension() {
        return this.fileExtension;
    }

    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    @Column(name = "contentRead")
    public Integer getContentRead() {
        return this.contentRead;
    }

    public void setContentRead(Integer contentRead) {
        this.contentRead = contentRead;
    }

    @Column(name = "contentPrint")
    public Integer getContentPrint() {
        return this.contentPrint;
    }

    public void setContentPrint(Integer contentPrint) {
        this.contentPrint = contentPrint;
    }

    @Column(name = "contentPrintHideWater")
    public Integer getContentPrintHideWater() {
        return this.contentPrintHideWater;
    }

    public void setContentPrintHideWater(Integer contentPrintHideWater) {
        this.contentPrintHideWater = contentPrintHideWater;
    }

    @Column(name = "contentModify")
    public Integer getContentModify() {
        return this.contentModify;
    }

    public void setContentModify(Integer contentModify) {
        this.contentModify = contentModify;
    }

    @Column(name = "contentScreenShot")
    public Integer getContentScreenShot() {
        return this.contentScreenShot;
    }

    public void setContentScreenShot(Integer contentScreenShot) {
        this.contentScreenShot = contentScreenShot;
    }

    @Column(name = "contentCopy")
    public Integer getContentCopy() {
        return this.contentCopy;
    }

    public void setContentCopy(Integer contentCopy) {
        this.contentCopy = contentCopy;
    }

    @Column(name = "fileCopy")
    public Integer getFileCopy() {
        return this.fileCopy;
    }

    public void setFileCopy(Integer fileCopy) {
        this.fileCopy = fileCopy;
    }

    @Column(name = "fileSaveCopy")
    public Integer getFileSaveCopy() {
        return this.fileSaveCopy;
    }

    public void setFileSaveCopy(Integer fileSaveCopy) {
        this.fileSaveCopy = fileSaveCopy;
    }

    @Column(name = "history", length = 4096, columnDefinition = "")
    public String getHistory() {
        return this.history;
    }

    public void setHistory(String history) {
        this.history = history;
    }

    @Column(name = "business")
    public String getBusiness() {
        return business;
    }

    public void setBusiness(String business) {
        this.business = business;
    }

    @Column(name = "outOfDate")
    public Integer getOutOfDate() {
        return outOfDate;
    }

    public void setOutOfDate(Integer outOfDate) {
        this.outOfDate = outOfDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fileByFkSrcFid")
    public List<ClientLog> getClientLogsForFkSrcFid() {
        return this.clientLogsForFkSrcFid;
    }

    public void setClientLogsForFkSrcFid(List<ClientLog> clientLogsForFkSrcFid) {
        this.clientLogsForFkSrcFid = clientLogsForFkSrcFid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "file")
    public List<FileLevelChangeHistory> getFileLevelChangeHistories() {
        return this.fileLevelChangeHistories;
    }

    public void setFileLevelChangeHistories(List<FileLevelChangeHistory> fileLevelChangeHistories) {
        this.fileLevelChangeHistories = fileLevelChangeHistories;
    }

}
