package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Group generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "Group", catalog = "dcms_db")
public class Group implements java.io.Serializable {

    private String pkGid;
    private Department department;
    private String name;
    private String description;
    private Long createTime;
    private Integer groupState;
    private List<UserToGroup> userToGroups = new ArrayList<UserToGroup>(0);

    public Group() {
    }

    public Group(String pkGid) {
        this.pkGid = pkGid;
    }

    public Group(String pkGid, Department department, String name, String description, Long createTime,
            Integer groupState, List<UserToGroup> userToGroups) {
        this.pkGid = pkGid;
        this.department = department;
        this.name = name;
        this.description = description;
        this.createTime = createTime;
        this.groupState = groupState;
        this.userToGroups = userToGroups;
    }

    @Id

    @Column(name = "pkGid", unique = true, nullable = false, length = 256)
    public String getPkGid() {
        return this.pkGid;
    }

    public void setPkGid(String pkGid) {
        this.pkGid = pkGid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkDid")
    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @Column(name = "name", length = 256, columnDefinition = "")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 256, columnDefinition = "")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "createTime")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "groupState")
    public Integer getGroupState() {
        return this.groupState;
    }

    public void setGroupState(Integer groupState) {
        this.groupState = groupState;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "group")
    public List<UserToGroup> getUserToGroups() {
        return this.userToGroups;
    }

    public void setUserToGroups(List<UserToGroup> userToGroups) {
        this.userToGroups = userToGroups;
    }

}
