package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MiddlewareAcl generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "MiddlewareACL", catalog = "dcms_db")
public class MiddlewareAcl implements java.io.Serializable {

    private Integer id;
    private Middleware middleware;
    private String ip;
    private Integer enable;
    private Integer passwdEnable;
    private String passwd;

    public MiddlewareAcl() {
    }

    public MiddlewareAcl(Middleware middleware, String ip, Integer enable, Integer passwdEnable, String passwd) {
        this.middleware = middleware;
        this.ip = ip;
        this.enable = enable;
        this.passwdEnable = passwdEnable;
        this.passwd = passwd;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkMiddlewareId")
    public Middleware getMiddleware() {
        return this.middleware;
    }

    public void setMiddleware(Middleware middleware) {
        this.middleware = middleware;
    }

    @Column(name = "ip", length = 256, columnDefinition = "")
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Column(name = "enable")
    public Integer getEnable() {
        return this.enable;
    }

    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    @Column(name = "passwdEnable")
    public Integer getPasswdEnable() {
        return this.passwdEnable;
    }

    public void setPasswdEnable(Integer passwdEnable) {
        this.passwdEnable = passwdEnable;
    }

    @Column(name = "passwd", length = 256, columnDefinition = "")
    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

}
