package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Middleware generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "Middleware", catalog = "dcms_db")
public class Middleware implements java.io.Serializable {

    private Integer id;
    private String name;
    private String description;
    private Integer enable;
    private List<MiddlewareAcl> middlewareAcls = new ArrayList<MiddlewareAcl>(0);

    public Middleware() {
    }

    public Middleware(String name, String description, Integer enable, List<MiddlewareAcl> middlewareAcls) {
        this.name = name;
        this.description = description;
        this.enable = enable;
        this.middlewareAcls = middlewareAcls;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", length = 265, columnDefinition = "")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 256, columnDefinition = "")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "enable")
    public Integer getEnable() {
        return this.enable;
    }

    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "middleware")
    public List<MiddlewareAcl> getMiddlewareAcls() {
        return this.middlewareAcls;
    }

    public void setMiddlewareAcls(List<MiddlewareAcl> middlewareAcls) {
        this.middlewareAcls = middlewareAcls;
    }

}
