package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleScope generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "RoleScope", catalog = "dcms_db")
public class RoleScope implements java.io.Serializable {

    private Integer id;
    private Role role;
    private String fkVarId;
    private Integer varType;
    private String varName;

    public RoleScope() {
    }

    public RoleScope(Role role, String fkVarId, Integer varType, String varName) {
        this.role = role;
        this.fkVarId = fkVarId;
        this.varType = varType;
        this.varName = varName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkRoleId")
    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    @Column(name = "fkVarId", length = 256, columnDefinition = "")
    public String getFkVarId() {
        return this.fkVarId;
    }

    public void setFkVarId(String fkVarId) {
        this.fkVarId = fkVarId;
    }

    @Column(name = "varType")
    public Integer getVarType() {
        return this.varType;
    }

    public void setVarType(Integer varType) {
        this.varType = varType;
    }

    @Column(name = "varName", length = 256, columnDefinition = "")
    public String getVarName() {
        return this.varName;
    }

    public void setVarName(String varName) {
        this.varName = varName;
    }

}
