package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "Role", catalog = "dcms_db")
public class Role implements java.io.Serializable {

    private Integer id;
    private User userByFkAgentUid;
    private User userByFkUid;
    private Long fkAgentInvalidTime;
    private Integer fileLevel;
    private Integer roleType;
    private List<RoleScope> roleScopes = new ArrayList<RoleScope>(0);
    private List<WorkflowPolicyStep> workflowPolicySteps = new ArrayList<WorkflowPolicyStep>(0);

    public Role() {
    }

    public Role(User userByFkAgentUid, User userByFkUid, Long fkAgentInvalidTime, Integer fileLevel, Integer roleType,
            List<RoleScope> roleScopes, List<WorkflowPolicyStep> workflowPolicySteps) {
        this.userByFkAgentUid = userByFkAgentUid;
        this.userByFkUid = userByFkUid;
        this.fkAgentInvalidTime = fkAgentInvalidTime;
        this.fileLevel = fileLevel;
        this.roleType = roleType;
        this.roleScopes = roleScopes;
        this.workflowPolicySteps = workflowPolicySteps;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkAgentUid")
    public User getUserByFkAgentUid() {
        return this.userByFkAgentUid;
    }

    public void setUserByFkAgentUid(User userByFkAgentUid) {
        this.userByFkAgentUid = userByFkAgentUid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkUid")
    public User getUserByFkUid() {
        return this.userByFkUid;
    }

    public void setUserByFkUid(User userByFkUid) {
        this.userByFkUid = userByFkUid;
    }

    @Column(name = "fkAgentInvalidTime")
    public Long getFkAgentInvalidTime() {
        return this.fkAgentInvalidTime;
    }

    public void setFkAgentInvalidTime(Long fkAgentInvalidTime) {
        this.fkAgentInvalidTime = fkAgentInvalidTime;
    }

    @Column(name = "fileLevel")
    public Integer getFileLevel() {
        return this.fileLevel;
    }

    public void setFileLevel(Integer fileLevel) {
        this.fileLevel = fileLevel;
    }

    @Column(name = "roleType")
    public Integer getRoleType() {
        return this.roleType;
    }

    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    public List<RoleScope> getRoleScopes() {
        return this.roleScopes;
    }

    public void setRoleScopes(List<RoleScope> roleScopes) {
        this.roleScopes = roleScopes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    public List<WorkflowPolicyStep> getWorkflowPolicySteps() {
        return this.workflowPolicySteps;
    }

    public void setWorkflowPolicySteps(List<WorkflowPolicyStep> workflowPolicySteps) {
        this.workflowPolicySteps = workflowPolicySteps;
    }

}
