package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StorageLocation generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "StorageLocation", catalog = "dcms_db")
public class StorageLocation implements java.io.Serializable {

    private Integer id;
    private String domainName;
    private String ip;
    private String port;
    private String filePath;
    private String protocol;
    private String account;
    private String passwd;
    private List<BackupHistory> backupHistories = new ArrayList<BackupHistory>(0);
    private List<File> files = new ArrayList<File>(0);
    private List<SystemConfig> systemConfigsForFkFileLevel1locationId = new ArrayList<SystemConfig>(0);
    private List<SystemConfig> systemConfigsForFkBackupLocationId = new ArrayList<SystemConfig>(0);
    private List<SystemConfig> systemConfigsForFkFileLevel5locationId = new ArrayList<SystemConfig>(0);
    private List<SystemConfig> systemConfigsForFkFileLevel4locationId = new ArrayList<SystemConfig>(0);
    private List<SystemConfig> systemConfigsForFkFileLevel3locationId = new ArrayList<SystemConfig>(0);
    private List<SystemConfig> systemConfigsForFkFileLevel2locationId = new ArrayList<SystemConfig>(0);
    private List<ClientPatch> clientPatches = new ArrayList<ClientPatch>(0);
    private List<SystemConfig> systemConfigsForFkAdAuthLocationId = new ArrayList<SystemConfig>(0);
    private List<SystemConfig> systemConfigsForFkLogLocationId = new ArrayList<SystemConfig>(0);

    public StorageLocation() {
    }

    public StorageLocation(String domainName, String ip, String port, String filePath, String protocol, String account,
            String passwd, List<BackupHistory> backupHistories, List<File> files,
            List<SystemConfig> systemConfigsForFkFileLevel1locationId,
            List<SystemConfig> systemConfigsForFkBackupLocationId,
            List<SystemConfig> systemConfigsForFkFileLevel5locationId,
            List<SystemConfig> systemConfigsForFkFileLevel4locationId,
            List<SystemConfig> systemConfigsForFkFileLevel3locationId,
            List<SystemConfig> systemConfigsForFkFileLevel2locationId, List<ClientPatch> clientPatches,
            List<SystemConfig> systemConfigsForFkAdAuthLocationId, List<SystemConfig> systemConfigsForFkLogLocationId) {
        this.domainName = domainName;
        this.ip = ip;
        this.port = port;
        this.filePath = filePath;
        this.protocol = protocol;
        this.account = account;
        this.passwd = passwd;
        this.backupHistories = backupHistories;
        this.files = files;
        this.systemConfigsForFkFileLevel1locationId = systemConfigsForFkFileLevel1locationId;
        this.systemConfigsForFkBackupLocationId = systemConfigsForFkBackupLocationId;
        this.systemConfigsForFkFileLevel5locationId = systemConfigsForFkFileLevel5locationId;
        this.systemConfigsForFkFileLevel4locationId = systemConfigsForFkFileLevel4locationId;
        this.systemConfigsForFkFileLevel3locationId = systemConfigsForFkFileLevel3locationId;
        this.systemConfigsForFkFileLevel2locationId = systemConfigsForFkFileLevel2locationId;
        this.clientPatches = clientPatches;
        this.systemConfigsForFkAdAuthLocationId = systemConfigsForFkAdAuthLocationId;
        this.systemConfigsForFkLogLocationId = systemConfigsForFkLogLocationId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "domainName", length = 256, columnDefinition = "")
    public String getDomainName() {
        return this.domainName;
    }

    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    @Column(name = "ip", length = 256, columnDefinition = "")
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Column(name = "port", length = 256, columnDefinition = "")
    public String getPort() {
        return this.port;
    }

    public void setPort(String port) {
        this.port = port;
    }

    @Column(name = "filePath", length = 256, columnDefinition = "")
    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(name = "protocol", length = 256, columnDefinition = "")
    public String getProtocol() {
        return this.protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    @Column(name = "account", length = 256, columnDefinition = "")
    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    @Column(name = "passwd", length = 256, columnDefinition = "")
    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocation")
    public List<BackupHistory> getBackupHistories() {
        return this.backupHistories;
    }

    public void setBackupHistories(List<BackupHistory> backupHistories) {
        this.backupHistories = backupHistories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocation")
    public List<File> getFiles() {
        return this.files;
    }

    public void setFiles(List<File> files) {
        this.files = files;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkFileLevel1locationId")
    public List<SystemConfig> getSystemConfigsForFkFileLevel1locationId() {
        return this.systemConfigsForFkFileLevel1locationId;
    }

    public void setSystemConfigsForFkFileLevel1locationId(List<SystemConfig> systemConfigsForFkFileLevel1locationId) {
        this.systemConfigsForFkFileLevel1locationId = systemConfigsForFkFileLevel1locationId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkBackupLocationId")
    public List<SystemConfig> getSystemConfigsForFkBackupLocationId() {
        return this.systemConfigsForFkBackupLocationId;
    }

    public void setSystemConfigsForFkBackupLocationId(List<SystemConfig> systemConfigsForFkBackupLocationId) {
        this.systemConfigsForFkBackupLocationId = systemConfigsForFkBackupLocationId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkFileLevel5locationId")
    public List<SystemConfig> getSystemConfigsForFkFileLevel5locationId() {
        return this.systemConfigsForFkFileLevel5locationId;
    }

    public void setSystemConfigsForFkFileLevel5locationId(List<SystemConfig> systemConfigsForFkFileLevel5locationId) {
        this.systemConfigsForFkFileLevel5locationId = systemConfigsForFkFileLevel5locationId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkFileLevel4locationId")
    public List<SystemConfig> getSystemConfigsForFkFileLevel4locationId() {
        return this.systemConfigsForFkFileLevel4locationId;
    }

    public void setSystemConfigsForFkFileLevel4locationId(List<SystemConfig> systemConfigsForFkFileLevel4locationId) {
        this.systemConfigsForFkFileLevel4locationId = systemConfigsForFkFileLevel4locationId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkFileLevel3locationId")
    public List<SystemConfig> getSystemConfigsForFkFileLevel3locationId() {
        return this.systemConfigsForFkFileLevel3locationId;
    }

    public void setSystemConfigsForFkFileLevel3locationId(List<SystemConfig> systemConfigsForFkFileLevel3locationId) {
        this.systemConfigsForFkFileLevel3locationId = systemConfigsForFkFileLevel3locationId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkFileLevel2locationId")
    public List<SystemConfig> getSystemConfigsForFkFileLevel2locationId() {
        return this.systemConfigsForFkFileLevel2locationId;
    }

    public void setSystemConfigsForFkFileLevel2locationId(List<SystemConfig> systemConfigsForFkFileLevel2locationId) {
        this.systemConfigsForFkFileLevel2locationId = systemConfigsForFkFileLevel2locationId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocation")
    public List<ClientPatch> getClientPatches() {
        return this.clientPatches;
    }

    public void setClientPatches(List<ClientPatch> clientPatches) {
        this.clientPatches = clientPatches;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkAdAuthLocationId")
    public List<SystemConfig> getSystemConfigsForFkAdAuthLocationId() {
        return this.systemConfigsForFkAdAuthLocationId;
    }

    public void setSystemConfigsForFkAdAuthLocationId(List<SystemConfig> systemConfigsForFkAdAuthLocationId) {
        this.systemConfigsForFkAdAuthLocationId = systemConfigsForFkAdAuthLocationId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "storageLocationByFkLogLocationId")
    public List<SystemConfig> getSystemConfigsForFkLogLocationId() {
        return this.systemConfigsForFkLogLocationId;
    }

    public void setSystemConfigsForFkLogLocationId(List<SystemConfig> systemConfigsForFkLogLocationId) {
        this.systemConfigsForFkLogLocationId = systemConfigsForFkLogLocationId;
    }

}
