package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SystemConfig generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Table(name = "SystemConfig", catalog = "dcms_db")
public class SystemConfig implements java.io.Serializable {

    private Integer id;
    private StorageLocation storageLocationByFkFileLevel1locationId;
    private StorageLocation storageLocationByFkBackupLocationId;
    private StorageLocation storageLocationByFkFileLevel5locationId;
    private StorageLocation storageLocationByFkFileLevel4locationId;
    private StorageLocation storageLocationByFkFileLevel3locationId;
    private StorageLocation storageLocationByFkFileLevel2locationId;
    private StorageLocation storageLocationByFkAdAuthLocationId;
    private StorageLocation storageLocationByFkLogLocationId;
    private StorageLocation storageLocationByFkPatchLocationId;
    private Integer systemTopLevel;
    private Integer autoBackupEnable;
    private String mailSenderAccount;
    private String mailSenderPasswd;
    private String mailSenderSmtpAddr;
    private String mailSenderSmtpPort;
    private Integer mailSenderSslenable;
    private String mailRecvResourceAccount;
    private String mailRecvResourceThreshold;
    private String mailRecvLogStorageAddr;
    private String mailRecvLogStorageThreshold;
    private String mailRecvFileStorageAddr;
    private String mailRecvFileStorageThreshold;
    private Integer localAuthEnable;
    private Integer localAuthPasswdMin;
    private Integer localAuthPasswdMax;
    private Integer localAuthPasswdContainsNumber;
    private Integer localAuthPasswdContainsLetter;
    private Integer localAuthPasswdContainsSpecial;
    private Integer localAuthPasswdLockThreshold;
    private Long localAuthPasswdLockTime;
    private Integer localAuthPasswdForceChange;
    private Long localAuthPasswdPeriod;
    private Integer localAuthUnlockByAdmin;
    private String localAuthInitPasswd;
    private Integer localAuthInitPasswdForceChange;
    private Integer adAuthEnable;
    private String adAuthDn;
    private Integer adAuthAutoSync;
    private String adAuthSyncRoot;
    private String watermarkContent;
    private Integer watermarkDispUser;
    private Integer watermarkDispDepartment;
    private Integer watermarkDispIp;
    private Integer watermarkDispPcName;
    private Integer watermarkDispPrintTime;
    private Integer watermarkDispAngle;
    private Integer watermarkDispAlpha;
    private Integer watermarkDispTextSize;
    private String watermarkDispTextColor;
    private Integer watermarkDispAlign;
    private String watermarkContentJson4Print;
    private String watermarkContentJson4Screen;
    private String masterServerIp;
    private String masterServerPort;
    private String reserveServerIp;
    private String reserveServerPort;
    private Long timerMailAlarmStartTime;
    private Long timerMailAlarmPeriod;
    private Long timerBackupStartTime;
    private Long timerBackupPerriod;
    private Long timerClientLogStartTime;
    private Long timerClientLogPeriod;
    private Long timerDirSyncStartTime;
    private Long timerDirSyncPeriod;
    private Long timerAutoDecodeStartTime;
    private Long timerAutoDecodePeriod;
    private Long timerFileStatisticStartTime;
    private Long timerFileStatisticPeriod;
    private Long timerCancelApproverStartTime;
    private Long timerCancelApproverPeriod;
    private String organizationCode;
    private String logArchiveKeepTime;
    private Integer autoLogArchiveEnable;
    private Integer preclassifiedForce;
    private String advancedControlStrategy;
    private String classifiedWhiteList;

    public SystemConfig() {
    }

    public SystemConfig(Integer id, StorageLocation storageLocationByFkFileLevel1locationId,
            StorageLocation storageLocationByFkBackupLocationId,
            StorageLocation storageLocationByFkFileLevel5locationId,
            StorageLocation storageLocationByFkFileLevel4locationId,
            StorageLocation storageLocationByFkFileLevel3locationId,
            StorageLocation storageLocationByFkFileLevel2locationId,
            StorageLocation storageLocationByFkAdAuthLocationId, StorageLocation storageLocationByFkLogLocationId,
            StorageLocation storageLocationByFkPatchLocationId, Integer systemTopLevel, Integer autoBackupEnable,
            String mailSenderAccount, String mailSenderPasswd, String mailSenderSmtpAddr, String mailSenderSmtpPort,
            Integer mailSenderSslenable, String mailRecvResourceAccount, String mailRecvResourceThreshold,
            String mailRecvLogStorageAddr, String mailRecvLogStorageThreshold, String mailRecvFileStorageAddr,
            String mailRecvFileStorageThreshold, Integer localAuthEnable, Integer localAuthPasswdMin,
            Integer localAuthPasswdMax, Integer localAuthPasswdContainsNumber, Integer localAuthPasswdContainsLetter,
            Integer localAuthPasswdContainsSpecial, Integer localAuthPasswdLockThreshold, Long localAuthPasswdLockTime,
            Integer localAuthPasswdForceChange, Long localAuthPasswdPeriod, Integer localAuthUnlockByAdmin,
            String localAuthInitPasswd, Integer localAuthInitPasswdForceChange, Integer adAuthEnable, String adAuthDn,
            Integer adAuthAutoSync, String adAuthSyncRoot, String watermarkContent, Integer watermarkDispUser,
            Integer watermarkDispDepartment, Integer watermarkDispIp, Integer watermarkDispPcName,
            Integer watermarkDispPrintTime, Integer watermarkDispAngle, Integer watermarkDispAlpha,
            Integer watermarkDispTextSize, String watermarkDispTextColor, Integer watermarkDispAlign,
            String watermarkContentJson4Print, String watermarkContentJson4Screen, String masterServerIp,
            String masterServerPort, String reserveServerIp, String reserveServerPort, Long timerMailAlarmStartTime,
            Long timerMailAlarmPeriod, Long timerBackupStartTime, Long timerBackupPerriod, Long timerClientLogStartTime,
            Long timerClientLogPeriod, Long timerDirSyncStartTime, Long timerDirSyncPeriod,
            Long timerAutoDecodeStartTime, Long timerAutoDecodePeriod, Long timerFileStatisticStartTime,
            Long timerFileStatisticPeriod, Long timerCancelApproverStartTime, Long timerCancelApproverPeriod,
            String organizationCode, String logArchiveKeepTime, Integer autoLogArchiveEnable,
            Integer preclassifiedForce, String advancedControlStrategy, String classifiedWhiteList) {
        this.id = id;
        this.storageLocationByFkFileLevel1locationId = storageLocationByFkFileLevel1locationId;
        this.storageLocationByFkBackupLocationId = storageLocationByFkBackupLocationId;
        this.storageLocationByFkFileLevel5locationId = storageLocationByFkFileLevel5locationId;
        this.storageLocationByFkFileLevel4locationId = storageLocationByFkFileLevel4locationId;
        this.storageLocationByFkFileLevel3locationId = storageLocationByFkFileLevel3locationId;
        this.storageLocationByFkFileLevel2locationId = storageLocationByFkFileLevel2locationId;
        this.storageLocationByFkAdAuthLocationId = storageLocationByFkAdAuthLocationId;
        this.storageLocationByFkLogLocationId = storageLocationByFkLogLocationId;
        this.storageLocationByFkPatchLocationId = storageLocationByFkPatchLocationId;
        this.systemTopLevel = systemTopLevel;
        this.autoBackupEnable = autoBackupEnable;
        this.mailSenderAccount = mailSenderAccount;
        this.mailSenderPasswd = mailSenderPasswd;
        this.mailSenderSmtpAddr = mailSenderSmtpAddr;
        this.mailSenderSmtpPort = mailSenderSmtpPort;
        this.mailSenderSslenable = mailSenderSslenable;
        this.mailRecvResourceAccount = mailRecvResourceAccount;
        this.mailRecvResourceThreshold = mailRecvResourceThreshold;
        this.mailRecvLogStorageAddr = mailRecvLogStorageAddr;
        this.mailRecvLogStorageThreshold = mailRecvLogStorageThreshold;
        this.mailRecvFileStorageAddr = mailRecvFileStorageAddr;
        this.mailRecvFileStorageThreshold = mailRecvFileStorageThreshold;
        this.localAuthEnable = localAuthEnable;
        this.localAuthPasswdMin = localAuthPasswdMin;
        this.localAuthPasswdMax = localAuthPasswdMax;
        this.localAuthPasswdContainsNumber = localAuthPasswdContainsNumber;
        this.localAuthPasswdContainsLetter = localAuthPasswdContainsLetter;
        this.localAuthPasswdContainsSpecial = localAuthPasswdContainsSpecial;
        this.localAuthPasswdLockThreshold = localAuthPasswdLockThreshold;
        this.localAuthPasswdLockTime = localAuthPasswdLockTime;
        this.localAuthPasswdForceChange = localAuthPasswdForceChange;
        this.localAuthPasswdPeriod = localAuthPasswdPeriod;
        this.localAuthUnlockByAdmin = localAuthUnlockByAdmin;
        this.localAuthInitPasswd = localAuthInitPasswd;
        this.localAuthInitPasswdForceChange = localAuthInitPasswdForceChange;
        this.adAuthEnable = adAuthEnable;
        this.adAuthDn = adAuthDn;
        this.adAuthAutoSync = adAuthAutoSync;
        this.adAuthSyncRoot = adAuthSyncRoot;
        this.watermarkContent = watermarkContent;
        this.watermarkDispUser = watermarkDispUser;
        this.watermarkDispDepartment = watermarkDispDepartment;
        this.watermarkDispIp = watermarkDispIp;
        this.watermarkDispPcName = watermarkDispPcName;
        this.watermarkDispPrintTime = watermarkDispPrintTime;
        this.watermarkDispAngle = watermarkDispAngle;
        this.watermarkDispAlpha = watermarkDispAlpha;
        this.watermarkDispTextSize = watermarkDispTextSize;
        this.watermarkDispTextColor = watermarkDispTextColor;
        this.watermarkDispAlign = watermarkDispAlign;
        this.watermarkContentJson4Print = watermarkContentJson4Print;
        this.watermarkContentJson4Screen = watermarkContentJson4Screen;
        this.masterServerIp = masterServerIp;
        this.masterServerPort = masterServerPort;
        this.reserveServerIp = reserveServerIp;
        this.reserveServerPort = reserveServerPort;
        this.timerMailAlarmStartTime = timerMailAlarmStartTime;
        this.timerMailAlarmPeriod = timerMailAlarmPeriod;
        this.timerBackupStartTime = timerBackupStartTime;
        this.timerBackupPerriod = timerBackupPerriod;
        this.timerClientLogStartTime = timerClientLogStartTime;
        this.timerClientLogPeriod = timerClientLogPeriod;
        this.timerDirSyncStartTime = timerDirSyncStartTime;
        this.timerDirSyncPeriod = timerDirSyncPeriod;
        this.timerAutoDecodeStartTime = timerAutoDecodeStartTime;
        this.timerAutoDecodePeriod = timerAutoDecodePeriod;
        this.timerFileStatisticStartTime = timerFileStatisticStartTime;
        this.timerFileStatisticPeriod = timerFileStatisticPeriod;
        this.timerCancelApproverStartTime = timerCancelApproverStartTime;
        this.timerCancelApproverPeriod = timerCancelApproverPeriod;
        this.organizationCode = organizationCode;
        this.logArchiveKeepTime = logArchiveKeepTime;
        this.autoLogArchiveEnable = autoLogArchiveEnable;
        this.preclassifiedForce = preclassifiedForce;
        this.advancedControlStrategy = advancedControlStrategy;
        this.classifiedWhiteList = classifiedWhiteList;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileLevel1LocationId")
    public StorageLocation getStorageLocationByFkFileLevel1locationId() {
        return this.storageLocationByFkFileLevel1locationId;
    }

    public void setStorageLocationByFkFileLevel1locationId(StorageLocation storageLocationByFkFileLevel1locationId) {
        this.storageLocationByFkFileLevel1locationId = storageLocationByFkFileLevel1locationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkBackupLocationId")
    public StorageLocation getStorageLocationByFkBackupLocationId() {
        return this.storageLocationByFkBackupLocationId;
    }

    public void setStorageLocationByFkBackupLocationId(StorageLocation storageLocationByFkBackupLocationId) {
        this.storageLocationByFkBackupLocationId = storageLocationByFkBackupLocationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileLevel5LocationId")
    public StorageLocation getStorageLocationByFkFileLevel5locationId() {
        return this.storageLocationByFkFileLevel5locationId;
    }

    public void setStorageLocationByFkFileLevel5locationId(StorageLocation storageLocationByFkFileLevel5locationId) {
        this.storageLocationByFkFileLevel5locationId = storageLocationByFkFileLevel5locationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileLevel4LocationId")
    public StorageLocation getStorageLocationByFkFileLevel4locationId() {
        return this.storageLocationByFkFileLevel4locationId;
    }

    public void setStorageLocationByFkFileLevel4locationId(StorageLocation storageLocationByFkFileLevel4locationId) {
        this.storageLocationByFkFileLevel4locationId = storageLocationByFkFileLevel4locationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileLevel3LocationId")
    public StorageLocation getStorageLocationByFkFileLevel3locationId() {
        return this.storageLocationByFkFileLevel3locationId;
    }

    public void setStorageLocationByFkFileLevel3locationId(StorageLocation storageLocationByFkFileLevel3locationId) {
        this.storageLocationByFkFileLevel3locationId = storageLocationByFkFileLevel3locationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkFileLevel2LocationId")
    public StorageLocation getStorageLocationByFkFileLevel2locationId() {
        return this.storageLocationByFkFileLevel2locationId;
    }

    public void setStorageLocationByFkFileLevel2locationId(StorageLocation storageLocationByFkFileLevel2locationId) {
        this.storageLocationByFkFileLevel2locationId = storageLocationByFkFileLevel2locationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkAdAuthLocationId")
    public StorageLocation getStorageLocationByFkAdAuthLocationId() {
        return this.storageLocationByFkAdAuthLocationId;
    }

    public void setStorageLocationByFkAdAuthLocationId(StorageLocation storageLocationByFkAdAuthLocationId) {
        this.storageLocationByFkAdAuthLocationId = storageLocationByFkAdAuthLocationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkLogLocationId")
    public StorageLocation getStorageLocationByFkLogLocationId() {
        return this.storageLocationByFkLogLocationId;
    }

    public void setStorageLocationByFkLogLocationId(StorageLocation storageLocationByFkLogLocationId) {
        this.storageLocationByFkLogLocationId = storageLocationByFkLogLocationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkPatchLocationId")
    public StorageLocation getStorageLocationByFkPatchLocationId() {
        return this.storageLocationByFkPatchLocationId;
    }

    public void setStorageLocationByFkPatchLocationId(StorageLocation storageLocationByFkPatchLocationId) {
        this.storageLocationByFkPatchLocationId = storageLocationByFkPatchLocationId;
    }

    @Column(name = "systemTopLevel")
    public Integer getSystemTopLevel() {
        return this.systemTopLevel;
    }

    public void setSystemTopLevel(Integer systemTopLevel) {
        this.systemTopLevel = systemTopLevel;
    }

    @Column(name = "autoBackupEnable")
    public Integer getAutoBackupEnable() {
        return this.autoBackupEnable;
    }

    public void setAutoBackupEnable(Integer autoBackupEnable) {
        this.autoBackupEnable = autoBackupEnable;
    }

    @Column(name = "mailSenderAccount", length = 256, columnDefinition = "")
    public String getMailSenderAccount() {
        return this.mailSenderAccount;
    }

    public void setMailSenderAccount(String mailSenderAccount) {
        this.mailSenderAccount = mailSenderAccount;
    }

    @Column(name = "mailSenderPasswd", length = 256, columnDefinition = "")
    public String getMailSenderPasswd() {
        return this.mailSenderPasswd;
    }

    public void setMailSenderPasswd(String mailSenderPasswd) {
        this.mailSenderPasswd = mailSenderPasswd;
    }

    @Column(name = "mailSenderSmtpAddr", length = 256, columnDefinition = "")
    public String getMailSenderSmtpAddr() {
        return this.mailSenderSmtpAddr;
    }

    public void setMailSenderSmtpAddr(String mailSenderSmtpAddr) {
        this.mailSenderSmtpAddr = mailSenderSmtpAddr;
    }

    @Column(name = "mailSenderSmtpPort", length = 256, columnDefinition = "")
    public String getMailSenderSmtpPort() {
        return this.mailSenderSmtpPort;
    }

    public void setMailSenderSmtpPort(String mailSenderSmtpPort) {
        this.mailSenderSmtpPort = mailSenderSmtpPort;
    }

    @Column(name = "mailSenderSSLEnable")
    public Integer getMailSenderSslenable() {
        return this.mailSenderSslenable;
    }

    public void setMailSenderSslenable(Integer mailSenderSslenable) {
        this.mailSenderSslenable = mailSenderSslenable;
    }

    @Column(name = "mailRecvResourceAccount", length = 256, columnDefinition = "")
    public String getMailRecvResourceAccount() {
        return this.mailRecvResourceAccount;
    }

    public void setMailRecvResourceAccount(String mailRecvResourceAccount) {
        this.mailRecvResourceAccount = mailRecvResourceAccount;
    }

    @Column(name = "mailRecvResourceThreshold", length = 256, columnDefinition = "")
    public String getMailRecvResourceThreshold() {
        return this.mailRecvResourceThreshold;
    }

    public void setMailRecvResourceThreshold(String mailRecvResourceThreshold) {
        this.mailRecvResourceThreshold = mailRecvResourceThreshold;
    }

    @Column(name = "mailRecvLogStorageAddr", length = 256, columnDefinition = "")
    public String getMailRecvLogStorageAddr() {
        return this.mailRecvLogStorageAddr;
    }

    public void setMailRecvLogStorageAddr(String mailRecvLogStorageAddr) {
        this.mailRecvLogStorageAddr = mailRecvLogStorageAddr;
    }

    @Column(name = "mailRecvLogStorageThreshold", length = 256, columnDefinition = "")
    public String getMailRecvLogStorageThreshold() {
        return this.mailRecvLogStorageThreshold;
    }

    public void setMailRecvLogStorageThreshold(String mailRecvLogStorageThreshold) {
        this.mailRecvLogStorageThreshold = mailRecvLogStorageThreshold;
    }

    @Column(name = "mailRecvFileStorageAddr", length = 256, columnDefinition = "")
    public String getMailRecvFileStorageAddr() {
        return this.mailRecvFileStorageAddr;
    }

    public void setMailRecvFileStorageAddr(String mailRecvFileStorageAddr) {
        this.mailRecvFileStorageAddr = mailRecvFileStorageAddr;
    }

    @Column(name = "mailRecvFileStorageThreshold", length = 256, columnDefinition = "")
    public String getMailRecvFileStorageThreshold() {
        return this.mailRecvFileStorageThreshold;
    }

    public void setMailRecvFileStorageThreshold(String mailRecvFileStorageThreshold) {
        this.mailRecvFileStorageThreshold = mailRecvFileStorageThreshold;
    }

    @Column(name = "localAuthEnable")
    public Integer getLocalAuthEnable() {
        return this.localAuthEnable;
    }

    public void setLocalAuthEnable(Integer localAuthEnable) {
        this.localAuthEnable = localAuthEnable;
    }

    @Column(name = "localAuthPasswdMin")
    public Integer getLocalAuthPasswdMin() {
        return this.localAuthPasswdMin;
    }

    public void setLocalAuthPasswdMin(Integer localAuthPasswdMin) {
        this.localAuthPasswdMin = localAuthPasswdMin;
    }

    @Column(name = "localAuthPasswdMax")
    public Integer getLocalAuthPasswdMax() {
        return this.localAuthPasswdMax;
    }

    public void setLocalAuthPasswdMax(Integer localAuthPasswdMax) {
        this.localAuthPasswdMax = localAuthPasswdMax;
    }

    @Column(name = "localAuthPasswdContainsNumber")
    public Integer getLocalAuthPasswdContainsNumber() {
        return this.localAuthPasswdContainsNumber;
    }

    public void setLocalAuthPasswdContainsNumber(Integer localAuthPasswdContainsNumber) {
        this.localAuthPasswdContainsNumber = localAuthPasswdContainsNumber;
    }

    @Column(name = "localAuthPasswdContainsLetter")
    public Integer getLocalAuthPasswdContainsLetter() {
        return this.localAuthPasswdContainsLetter;
    }

    public void setLocalAuthPasswdContainsLetter(Integer localAuthPasswdContainsLetter) {
        this.localAuthPasswdContainsLetter = localAuthPasswdContainsLetter;
    }

    @Column(name = "localAuthPasswdContainsSpecial")
    public Integer getLocalAuthPasswdContainsSpecial() {
        return this.localAuthPasswdContainsSpecial;
    }

    public void setLocalAuthPasswdContainsSpecial(Integer localAuthPasswdContainsSpecial) {
        this.localAuthPasswdContainsSpecial = localAuthPasswdContainsSpecial;
    }

    @Column(name = "localAuthPasswdLockThreshold")
    public Integer getLocalAuthPasswdLockThreshold() {
        return this.localAuthPasswdLockThreshold;
    }

    public void setLocalAuthPasswdLockThreshold(Integer localAuthPasswdLockThreshold) {
        this.localAuthPasswdLockThreshold = localAuthPasswdLockThreshold;
    }

    @Column(name = "localAuthPasswdLockTime")
    public Long getLocalAuthPasswdLockTime() {
        return this.localAuthPasswdLockTime;
    }

    public void setLocalAuthPasswdLockTime(Long localAuthPasswdLockTime) {
        this.localAuthPasswdLockTime = localAuthPasswdLockTime;
    }

    @Column(name = "localAuthPasswdForceChange")
    public Integer getLocalAuthPasswdForceChange() {
        return this.localAuthPasswdForceChange;
    }

    public void setLocalAuthPasswdForceChange(Integer localAuthPasswdForceChange) {
        this.localAuthPasswdForceChange = localAuthPasswdForceChange;
    }

    @Column(name = "localAuthPasswdPeriod")
    public Long getLocalAuthPasswdPeriod() {
        return this.localAuthPasswdPeriod;
    }

    public void setLocalAuthPasswdPeriod(Long localAuthPasswdPeriod) {
        this.localAuthPasswdPeriod = localAuthPasswdPeriod;
    }

    @Column(name = "localAuthUnlockByAdmin")
    public Integer getLocalAuthUnlockByAdmin() {
        return this.localAuthUnlockByAdmin;
    }

    public void setLocalAuthUnlockByAdmin(Integer localAuthUnlockByAdmin) {
        this.localAuthUnlockByAdmin = localAuthUnlockByAdmin;
    }

    @Column(name = "localAuthInitPasswd", length = 256, columnDefinition = "")
    public String getLocalAuthInitPasswd() {
        return this.localAuthInitPasswd;
    }

    public void setLocalAuthInitPasswd(String localAuthInitPasswd) {
        this.localAuthInitPasswd = localAuthInitPasswd;
    }

    @Column(name = "localAuthInitPasswdForceChange")
    public Integer getLocalAuthInitPasswdForceChange() {
        return this.localAuthInitPasswdForceChange;
    }

    public void setLocalAuthInitPasswdForceChange(Integer localAuthInitPasswdForceChange) {
        this.localAuthInitPasswdForceChange = localAuthInitPasswdForceChange;
    }

    @Column(name = "adAuthEnable")
    public Integer getAdAuthEnable() {
        return this.adAuthEnable;
    }

    public void setAdAuthEnable(Integer adAuthEnable) {
        this.adAuthEnable = adAuthEnable;
    }

    @Column(name = "adAuthDn", length = 256, columnDefinition = "")
    public String getAdAuthDn() {
        return this.adAuthDn;
    }

    public void setAdAuthDn(String adAuthDn) {
        this.adAuthDn = adAuthDn;
    }

    @Column(name = "adAuthAutoSync")
    public Integer getAdAuthAutoSync() {
        return this.adAuthAutoSync;
    }

    public void setAdAuthAutoSync(Integer adAuthAutoSync) {
        this.adAuthAutoSync = adAuthAutoSync;
    }

    @Column(name = "adAuthSyncRoot", length = 256, columnDefinition = "")
    public String getAdAuthSyncRoot() {
        return this.adAuthSyncRoot;
    }

    public void setAdAuthSyncRoot(String adAuthSyncRoot) {
        this.adAuthSyncRoot = adAuthSyncRoot;
    }

    @Column(name = "watermarkContent", length = 256, columnDefinition = "")
    public String getWatermarkContent() {
        return this.watermarkContent;
    }

    public void setWatermarkContent(String watermarkContent) {
        this.watermarkContent = watermarkContent;
    }

    @Column(name = "watermarkDispUser")
    public Integer getWatermarkDispUser() {
        return this.watermarkDispUser;
    }

    public void setWatermarkDispUser(Integer watermarkDispUser) {
        this.watermarkDispUser = watermarkDispUser;
    }

    @Column(name = "watermarkDispDepartment")
    public Integer getWatermarkDispDepartment() {
        return this.watermarkDispDepartment;
    }

    public void setWatermarkDispDepartment(Integer watermarkDispDepartment) {
        this.watermarkDispDepartment = watermarkDispDepartment;
    }

    @Column(name = "watermarkDispIp")
    public Integer getWatermarkDispIp() {
        return this.watermarkDispIp;
    }

    public void setWatermarkDispIp(Integer watermarkDispIp) {
        this.watermarkDispIp = watermarkDispIp;
    }

    @Column(name = "watermarkDispPcName")
    public Integer getWatermarkDispPcName() {
        return this.watermarkDispPcName;
    }

    public void setWatermarkDispPcName(Integer watermarkDispPcName) {
        this.watermarkDispPcName = watermarkDispPcName;
    }

    @Column(name = "watermarkDispPrintTime")
    public Integer getWatermarkDispPrintTime() {
        return this.watermarkDispPrintTime;
    }

    public void setWatermarkDispPrintTime(Integer watermarkDispPrintTime) {
        this.watermarkDispPrintTime = watermarkDispPrintTime;
    }

    @Column(name = "watermarkDispAngle")
    public Integer getWatermarkDispAngle() {
        return this.watermarkDispAngle;
    }

    public void setWatermarkDispAngle(Integer watermarkDispAngle) {
        this.watermarkDispAngle = watermarkDispAngle;
    }

    @Column(name = "watermarkDispAlpha")
    public Integer getWatermarkDispAlpha() {
        return this.watermarkDispAlpha;
    }

    public void setWatermarkDispAlpha(Integer watermarkDispAlpha) {
        this.watermarkDispAlpha = watermarkDispAlpha;
    }

    @Column(name = "watermarkDispTextSize")
    public Integer getWatermarkDispTextSize() {
        return this.watermarkDispTextSize;
    }

    public void setWatermarkDispTextSize(Integer watermarkDispTextSize) {
        this.watermarkDispTextSize = watermarkDispTextSize;
    }

    @Column(name = "watermarkDispTextColor", length = 256, columnDefinition = "")
    public String getWatermarkDispTextColor() {
        return this.watermarkDispTextColor;
    }

    public void setWatermarkDispTextColor(String watermarkDispTextColor) {
        this.watermarkDispTextColor = watermarkDispTextColor;
    }

    @Column(name = "watermarkDispAlign")
    public Integer getWatermarkDispAlign() {
        return this.watermarkDispAlign;
    }

    public void setWatermarkDispAlign(Integer watermarkDispAlign) {
        this.watermarkDispAlign = watermarkDispAlign;
    }

    @Column(name = "watermarkContentJson4Print")
    public String getWatermarkContentJson4Print() {
        return watermarkContentJson4Print;
    }

    public void setWatermarkContentJson4Print(String watermarkContentJson4Print) {
        this.watermarkContentJson4Print = watermarkContentJson4Print;
    }

    @Column(name = "watermarkContentJson4Screen")
    public String getWatermarkContentJson4Screen() {
        return watermarkContentJson4Screen;
    }

    public void setWatermarkContentJson4Screen(String watermarkContentJson4Screen) {
        this.watermarkContentJson4Screen = watermarkContentJson4Screen;
    }

    @Column(name = "masterServerIp", length = 256, columnDefinition = "")
    public String getMasterServerIp() {
        return this.masterServerIp;
    }

    public void setMasterServerIp(String masterServerIp) {
        this.masterServerIp = masterServerIp;
    }

    @Column(name = "masterServerPort", length = 256, columnDefinition = "")
    public String getMasterServerPort() {
        return this.masterServerPort;
    }

    public void setMasterServerPort(String masterServerPort) {
        this.masterServerPort = masterServerPort;
    }

    @Column(name = "reserveServerIp", length = 256, columnDefinition = "")
    public String getReserveServerIp() {
        return this.reserveServerIp;
    }

    public void setReserveServerIp(String reserveServerIp) {
        this.reserveServerIp = reserveServerIp;
    }

    @Column(name = "reserveServerPort", length = 256, columnDefinition = "")
    public String getReserveServerPort() {
        return this.reserveServerPort;
    }

    public void setReserveServerPort(String reserveServerPort) {
        this.reserveServerPort = reserveServerPort;
    }

    @Column(name = "timerMailAlarmStartTime")
    public Long getTimerMailAlarmStartTime() {
        return this.timerMailAlarmStartTime;
    }

    public void setTimerMailAlarmStartTime(Long timerMailAlarmStartTime) {
        this.timerMailAlarmStartTime = timerMailAlarmStartTime;
    }

    @Column(name = "timerMailAlarmPeriod")
    public Long getTimerMailAlarmPeriod() {
        return this.timerMailAlarmPeriod;
    }

    public void setTimerMailAlarmPeriod(Long timerMailAlarmPeriod) {
        this.timerMailAlarmPeriod = timerMailAlarmPeriod;
    }

    @Column(name = "timerBackupStartTime")
    public Long getTimerBackupStartTime() {
        return this.timerBackupStartTime;
    }

    public void setTimerBackupStartTime(Long timerBackupStartTime) {
        this.timerBackupStartTime = timerBackupStartTime;
    }

    @Column(name = "timerBackupPerriod")
    public Long getTimerBackupPerriod() {
        return this.timerBackupPerriod;
    }

    public void setTimerBackupPerriod(Long timerBackupPerriod) {
        this.timerBackupPerriod = timerBackupPerriod;
    }

    @Column(name = "timerClientLogStartTime")
    public Long getTimerClientLogStartTime() {
        return this.timerClientLogStartTime;
    }

    public void setTimerClientLogStartTime(Long timerClientLogStartTime) {
        this.timerClientLogStartTime = timerClientLogStartTime;
    }

    @Column(name = "timerClientLogPeriod")
    public Long getTimerClientLogPeriod() {
        return this.timerClientLogPeriod;
    }

    public void setTimerClientLogPeriod(Long timerClientLogPeriod) {
        this.timerClientLogPeriod = timerClientLogPeriod;
    }

    @Column(name = "timerDirSyncStartTime")
    public Long getTimerDirSyncStartTime() {
        return this.timerDirSyncStartTime;
    }

    public void setTimerDirSyncStartTime(Long timerDirSyncStartTime) {
        this.timerDirSyncStartTime = timerDirSyncStartTime;
    }

    @Column(name = "timerDirSyncPeriod")
    public Long getTimerDirSyncPeriod() {
        return this.timerDirSyncPeriod;
    }

    public void setTimerDirSyncPeriod(Long timerDirSyncPeriod) {
        this.timerDirSyncPeriod = timerDirSyncPeriod;
    }

    @Column(name = "timerAutoDecodeStartTime")
    public Long getTimerAutoDecodeStartTime() {
        return this.timerAutoDecodeStartTime;
    }

    public void setTimerAutoDecodeStartTime(Long timerAutoDecodeStartTime) {
        this.timerAutoDecodeStartTime = timerAutoDecodeStartTime;
    }

    @Column(name = "timerAutoDecodePeriod")
    public Long getTimerAutoDecodePeriod() {
        return this.timerAutoDecodePeriod;
    }

    public void setTimerAutoDecodePeriod(Long timerAutoDecodePeriod) {
        this.timerAutoDecodePeriod = timerAutoDecodePeriod;
    }

    @Column(name = "timerFileStatisticStartTime")
    public Long getTimerFileStatisticStartTime() {
        return this.timerFileStatisticStartTime;
    }

    public void setTimerFileStatisticStartTime(Long timerFileStatisticStartTime) {
        this.timerFileStatisticStartTime = timerFileStatisticStartTime;
    }

    @Column(name = "timerFileStatisticPeriod")
    public Long getTimerFileStatisticPeriod() {
        return this.timerFileStatisticPeriod;
    }

    public void setTimerFileStatisticPeriod(Long timerFileStatisticPeriod) {
        this.timerFileStatisticPeriod = timerFileStatisticPeriod;
    }

    @Column(name = "timerCancelApproverStartTime")
    public Long getTimerCancelApproverStartTime() {
        return this.timerCancelApproverStartTime;
    }

    public void setTimerCancelApproverStartTime(Long timerCancelApproverStartTime) {
        this.timerCancelApproverStartTime = timerCancelApproverStartTime;
    }

    @Column(name = "timerCancelApproverPeriod")
    public Long getTimerCancelApproverPeriod() {
        return this.timerCancelApproverPeriod;
    }

    public void setTimerCancelApproverPeriod(Long timerCancelApproverPeriod) {
        this.timerCancelApproverPeriod = timerCancelApproverPeriod;
    }

    @Column(name = "organizationCode", length = 256, columnDefinition = "")
    public String getOrganizationCode() {
        return organizationCode;
    }

    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
    }

    @Column(name = "logArchiveKeepTime", length = 256, columnDefinition = "")
    public String getLogArchiveKeepTime() {
        return logArchiveKeepTime;
    }

    public void setLogArchiveKeepTime(String logArchiveKeepTime) {
        this.logArchiveKeepTime = logArchiveKeepTime;
    }

    @Column(name = "autoLogArchiveEnable")
    public Integer getAutoLogArchiveEnable() {
        return this.autoLogArchiveEnable;
    }

    public void setAutoLogArchiveEnable(Integer autoLogArchiveEnable) {
        this.autoLogArchiveEnable = autoLogArchiveEnable;
    }

    @Column(name = "preclassifiedForce")
    public Integer getPreclassifiedForce() {
        return preclassifiedForce;
    }

    public void setPreclassifiedForce(Integer preclassifiedForce) {
        this.preclassifiedForce = preclassifiedForce;
    }

    @Column(name = "advancedControlStrategy")
    public String getAdvancedControlStrategy() {
        return advancedControlStrategy;
    }

    public void setAdvancedControlStrategy(String advancedControlStrategy) {
        this.advancedControlStrategy = advancedControlStrategy;
    }

    @Column(name = "classifiedWhiteList")
    public String getClassifiedWhiteList() {
        return classifiedWhiteList;
    }

    public void setClassifiedWhiteList(String classifiedWhiteList) {
        this.classifiedWhiteList = classifiedWhiteList;
    }

}
