package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Table(name = "UserMessage", catalog = "dcms_db")
public class UserMessage implements java.io.Serializable {

    private Integer id;
    private String fkUid;
    private String message;

    public UserMessage() {
    }

    public UserMessage(String fkUid, String message) {
        this.fkUid = fkUid;
        this.message = message;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "fkUid", length = 256)
    public String getFkUid() {
        return fkUid;
    }

    public void setFkUid(String fkUid) {
        this.fkUid = fkUid;
    }

    @Column(name = "message", length = 256, columnDefinition = "")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
