package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WorkflowPolicy generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "WorkflowPolicy", catalog = "dcms_db")
public class WorkflowPolicy implements java.io.Serializable {

    private Integer id;
    private Integer workFlowType;
    private Integer fileLevel;
    private Long createTime;

    public WorkflowPolicy() {
    }

    public WorkflowPolicy(Integer workFlowType, Integer fileLevel, Long createTime) {
        this.workFlowType = workFlowType;
        this.fileLevel = fileLevel;
        this.createTime = createTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "workFlowType")
    public Integer getWorkFlowType() {
        return this.workFlowType;
    }

    public void setWorkFlowType(Integer workFlowType) {
        this.workFlowType = workFlowType;
    }

    @Column(name = "fileLevel")
    public Integer getFileLevel() {
        return this.fileLevel;
    }

    public void setFileLevel(Integer fileLevel) {
        this.fileLevel = fileLevel;
    }

    @Column(name = "createTime")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

}
