package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Workflow generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
@Table(name = "Workflow", catalog = "dcms_db")
public class Workflow implements java.io.Serializable {

    private Integer id;
    private User user;
    private Integer workFlowType;
    private String fkSrcFid;
    private String fkDesFid;
    private Integer applyFileLevel;
    private String applyValidPeriod;
    private Integer durationType;
    private String durationDescription;
    private Long fileDecryptTime;
    private String applyBasis;
    private Integer applyBasisType;
    private String applyBasisDesc;
    private String applyMajorUnit;
    private String applyMinorUnit;
    private String applyDispatch;
    private String applyDispatchDesc;
    private String flowTrack;
    private Integer flowState;
    private Long createTime;
    private String createComment;
    private Integer totalStep;
    private Integer currentStep;
    private String permission;
    private String issueNumber;
    private Integer docNumber;
    private Integer duplicationAmount;
    private Integer markVersion;
    private Integer urgency;
    private String fileName;
    private Integer flowResult;
    private String business;
    private List<WorkflowTrack> workflowTracks = new ArrayList<WorkflowTrack>(0);

    public Workflow() {
    }

    public Workflow(User user, Integer workFlowType, String fkSrcFid, String fkDesFid, Integer applyFileLevel,
            String applyValidPeriod, Integer durationType, String durationDescription, Long fileDecryptTime,
            String applyBasis, Integer applyBasisType, String applyBasisDesc, String applyMajorUnit,
            String applyMinorUnit, String applyDispatch, String applyDispatchDesc, String flowTrack, Integer flowState,
            Long createTime, String createComment, Integer totalStep, Integer currentStep, String permission,
            String issueNumber, Integer docNumber, Integer duplicationAmount, Integer markVersion, Integer urgency,
            String fileName, Integer flowResult, String business, List<WorkflowTrack> workflowTracks) {
        this.user = user;
        this.workFlowType = workFlowType;
        this.fkSrcFid = fkSrcFid;
        this.fkDesFid = fkDesFid;
        this.applyFileLevel = applyFileLevel;
        this.applyValidPeriod = applyValidPeriod;
        this.durationType = durationType;
        this.durationDescription = durationDescription;
        this.fileDecryptTime = fileDecryptTime;
        this.applyBasis = applyBasis;
        this.applyBasisType = applyBasisType;
        this.applyBasisDesc = applyBasisDesc;
        this.applyMajorUnit = applyMajorUnit;
        this.applyMinorUnit = applyMinorUnit;
        this.applyDispatch = applyDispatch;
        this.applyDispatchDesc = applyDispatchDesc;
        this.flowTrack = flowTrack;
        this.flowState = flowState;
        this.createTime = createTime;
        this.createComment = createComment;
        this.totalStep = totalStep;
        this.currentStep = currentStep;
        this.permission = permission;
        this.issueNumber = issueNumber;
        this.docNumber = docNumber;
        this.duplicationAmount = duplicationAmount;
        this.markVersion = markVersion;
        this.urgency = urgency;
        this.fileName = fileName;
        this.flowResult = flowResult;
        this.business = business;
        this.workflowTracks = workflowTracks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkCreateUid")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "workFlowType")
    public Integer getWorkFlowType() {
        return this.workFlowType;
    }

    public void setWorkFlowType(Integer workFlowType) {
        this.workFlowType = workFlowType;
    }

    @Column(name = "fkSrcFid", length = 256, columnDefinition = "")
    public String getFkSrcFid() {
        return this.fkSrcFid;
    }

    public void setFkSrcFid(String fkSrcFid) {
        this.fkSrcFid = fkSrcFid;
    }

    @Column(name = "fkDesFid", length = 256, columnDefinition = "")
    public String getFkDesFid() {
        return this.fkDesFid;
    }

    public void setFkDesFid(String fkDesFid) {
        this.fkDesFid = fkDesFid;
    }

    @Column(name = "applyFileLevel")
    public Integer getApplyFileLevel() {
        return this.applyFileLevel;
    }

    public void setApplyFileLevel(Integer applyFileLevel) {
        this.applyFileLevel = applyFileLevel;
    }

    @Column(name = "applyValidPeriod", length = 20, columnDefinition = "")
    public String getApplyValidPeriod() {
        return this.applyValidPeriod;
    }

    public void setApplyValidPeriod(String applyValidPeriod) {
        this.applyValidPeriod = applyValidPeriod;
    }

    @Column(name = "durationType")
    public Integer getDurationType() {
        return this.durationType;
    }

    public void setDurationType(Integer durationType) {
        this.durationType = durationType;
    }

    @Column(name = "durationDescription", length = 1024, columnDefinition = "")
    public String getDurationDescription() {
        return this.durationDescription;
    }

    public void setDurationDescription(String durationDescription) {
        this.durationDescription = durationDescription;
    }

    @Column(name = "fileDecryptTime")
    public Long getFileDecryptTime() {
        return this.fileDecryptTime;
    }

    public void setFileDecryptTime(Long fileDecryptTime) {
        this.fileDecryptTime = fileDecryptTime;
    }

    @Column(name = "applyBasis", columnDefinition = "text")
    public String getApplyBasis() {
        return this.applyBasis;
    }

    public void setApplyBasis(String applyBasis) {
        this.applyBasis = applyBasis;
    }

    @Column(name = "applyBasisType")
    public Integer getApplyBasisType() {
        return this.applyBasisType;
    }

    public void setApplyBasisType(Integer applyBasisType) {
        this.applyBasisType = applyBasisType;
    }

    @Column(name = "applyBasisDesc", length = 1024, columnDefinition = "")
    public String getApplyBasisDesc() {
        return this.applyBasisDesc;
    }

    public void setApplyBasisDesc(String applyBasisDesc) {
        this.applyBasisDesc = applyBasisDesc;
    }

    @Column(name = "applyMajorUnit", length = 256, columnDefinition = "")
    public String getApplyMajorUnit() {
        return this.applyMajorUnit;
    }

    public void setApplyMajorUnit(String applyMajorUnit) {
        this.applyMajorUnit = applyMajorUnit;
    }

    @Column(name = "applyMinorUnit", length = 256, columnDefinition = "")
    public String getApplyMinorUnit() {
        return this.applyMinorUnit;
    }

    public void setApplyMinorUnit(String applyMinorUnit) {
        this.applyMinorUnit = applyMinorUnit;
    }

    @Column(name = "applyDispatch", columnDefinition = "text")
    public String getApplyDispatch() {
        return this.applyDispatch;
    }

    public void setApplyDispatch(String applyDispatch) {
        this.applyDispatch = applyDispatch;
    }

    @Column(name = "applyDispatchDesc", length = 1024, columnDefinition = "")
    public String getApplyDispatchDesc() {
        return this.applyDispatchDesc;
    }

    public void setApplyDispatchDesc(String applyDispatchDesc) {
        this.applyDispatchDesc = applyDispatchDesc;
    }

    @Column(name = "flowTrack", length = 1024, columnDefinition = "")
    public String getFlowTrack() {
        return this.flowTrack;
    }

    public void setFlowTrack(String flowTrack) {
        this.flowTrack = flowTrack;
    }

    @Column(name = "flowState")
    public Integer getFlowState() {
        return this.flowState;
    }

    public void setFlowState(Integer flowState) {
        this.flowState = flowState;
    }

    @Column(name = "createTime")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "createComment", length = 256, columnDefinition = "")
    public String getCreateComment() {
        return this.createComment;
    }

    public void setCreateComment(String createComment) {
        this.createComment = createComment;
    }

    @Column(name = "totalStep")
    public Integer getTotalStep() {
        return this.totalStep;
    }

    public void setTotalStep(Integer totalStep) {
        this.totalStep = totalStep;
    }

    @Column(name = "currentStep")
    public Integer getCurrentStep() {
        return this.currentStep;
    }

    public void setCurrentStep(Integer currentStep) {
        this.currentStep = currentStep;
    }

    @Column(name = "permission", length = 1024, columnDefinition = "")
    public String getPermission() {
        return this.permission;
    }

    public void setPermission(String permission) {
        this.permission = permission;
    }

    @Column(name = "issueNumber", length = 50, columnDefinition = "")
    public String getIssueNumber() {
        return this.issueNumber;
    }

    public void setIssueNumber(String issueNumber) {
        this.issueNumber = issueNumber;
    }

    @Column(name = "docNumber")
    public Integer getDocNumber() {
        return this.docNumber;
    }

    public void setDocNumber(Integer docNumber) {
        this.docNumber = docNumber;
    }

    @Column(name = "duplicationAmount")
    public Integer getDuplicationAmount() {
        return this.duplicationAmount;
    }

    public void setDuplicationAmount(Integer duplicationAmount) {
        this.duplicationAmount = duplicationAmount;
    }

    @Column(name = "markVersion")
    public Integer getMarkVersion() {
        return this.markVersion;
    }

    public void setMarkVersion(Integer markVersion) {
        this.markVersion = markVersion;
    }

    @Column(name = "urgency")
    public Integer getUrgency() {
        return this.urgency;
    }

    public void setUrgency(Integer urgency) {
        this.urgency = urgency;
    }

    @Column(name = "fileName", length = 256, columnDefinition = "")
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "flowResult")
    public Integer getFlowResult() {
        return flowResult;
    }

    public void setFlowResult(Integer flowResult) {
        this.flowResult = flowResult;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "workflow")
    public List<WorkflowTrack> getWorkflowTracks() {
        return this.workflowTracks;
    }

    public void setWorkflowTracks(List<WorkflowTrack> workflowTracks) {
        this.workflowTracks = workflowTracks;
    }

    @Column(name = "business")
    public String getBusiness() {
        return business;
    }

    public void setBusiness(String business) {
        this.business = business;
    }

}
