package cn.bestsec.dcms.platform.entity;
// Generated 2017-3-22 10:33:46 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WorkflowTrack generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true)  
@Table(name = "WorkflowTrack", catalog = "dcms_db")
public class WorkflowTrack implements java.io.Serializable {

    private Integer id;
    private User user;
    private Workflow workflow;
    private Integer approveStep;
    private Integer approveState;
    private String approveComment;
    private Long approveTime;

    public WorkflowTrack() {
    }

    public WorkflowTrack(User user, Workflow workflow, Integer approveStep, Integer approveState, String approveComment,
            Long approveTime) {
        this.user = user;
        this.workflow = workflow;
        this.approveStep = approveStep;
        this.approveState = approveState;
        this.approveComment = approveComment;
        this.approveTime = approveTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkApproveUid")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fkWorkFlowId")
    public Workflow getWorkflow() {
        return this.workflow;
    }

    public void setWorkflow(Workflow workflow) {
        this.workflow = workflow;
    }

    @Column(name = "approveStep")
    public Integer getApproveStep() {
        return this.approveStep;
    }

    public void setApproveStep(Integer approveStep) {
        this.approveStep = approveStep;
    }

    @Column(name = "approveState")
    public Integer getApproveState() {
        return this.approveState;
    }

    public void setApproveState(Integer approveState) {
        this.approveState = approveState;
    }

    @Column(name = "approveComment", length = 256, columnDefinition = "")
    public String getApproveComment() {
        return this.approveComment;
    }

    public void setApproveComment(String approveComment) {
        this.approveComment = approveComment;
    }

    @Column(name = "approveTime")
    public Long getApproveTime() {
        return this.approveTime;
    }

    public void setApproveTime(Long approveTime) {
        this.approveTime = approveTime;
    }

}
